apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: LoadBalancer
  selector:
    app: my-spring-boot-app
  ports:
    - protocol: TCP
      port: 8083           # Port sur lequel ton application écoute dans le conteneur
      targetPort: 8083      # Port exposé vers ton application